"""init schema

Revision ID: 71f8b524a7a1
Revises: 
Create Date: 2026-03-01 23:29:02.341271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f8b524a7a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('blocked_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_ranges_end_at'), 'blocked_ranges', ['end_at'], unique=False)
    op.create_index(op.f('ix_blocked_ranges_start_at'), 'blocked_ranges', ['start_at'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'HELD', 'BOOKED', name='slot_status'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_at', name='uq_time_slots_start_at')
    )
    op.create_index(op.f('ix_time_slots_hold_expires_at'), 'time_slots', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_time_slots_start_at'), 'time_slots', ['start_at'], unique=False)
    op.create_table('weekly_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_breaks_weekday'), 'weekly_breaks', ['weekday'], unique=False)
    op.create_table('weekly_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekday', name='uq_weekly_schedule_weekday')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('HOLD', 'PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='booking_status'), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_customer_email'), 'bookings', ['customer_email'], unique=False)
    op.create_index(op.f('ix_bookings_stripe_payment_intent_id'), 'bookings', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_bookings_time_slot_id'), 'bookings', ['time_slot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_time_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_stripe_payment_intent_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_email'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('weekly_schedule')
    op.drop_index(op.f('ix_weekly_breaks_weekday'), table_name='weekly_breaks')
    op.drop_table('weekly_breaks')
    op.drop_index(op.f('ix_time_slots_start_at'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_hold_expires_at'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_blocked_ranges_start_at'), table_name='blocked_ranges')
    op.drop_index(op.f('ix_blocked_ranges_end_at'), table_name='blocked_ranges')
    op.drop_table('blocked_ranges')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
